import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import axios from 'axios';
import toast from 'react-hot-toast';

const SymptomCheckerPage = () => {
  const [symptoms, setSymptoms] = useState('');
  const [result, setResult] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsLoading(true);
    setResult('');
    try {
      const token = localStorage.getItem('token');
      const { data } = await axios.post(
        `${import.meta.env.VITE_API_URL}/ai/symptom-checker`,
        { symptoms },
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setResult(data.result);
    } catch (error) {
      toast.error("Failed to get a response. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50/50 pt-32 pb-24">
      <div className="container mx-auto px-6 max-w-5xl">
        <div className="text-center mb-16 animate-in fade-in slide-in-from-bottom-4 duration-700">
          <div className="inline-block px-4 py-1.5 rounded-full bg-indigo-50 text-indigo-600 text-[10px] font-black uppercase tracking-widest mb-4">
            AI Diagnostic Protocol
          </div>
          <h1 className="text-4xl md:text-5xl font-extrabold text-slate-900 tracking-tight mb-4">
            Symptom <span className="text-gradient">Analysis Utility</span>
          </h1>
          <p className="text-slate-500 font-medium max-w-2xl mx-auto text-lg">
            Describe your clinical manifestations in natural language. Our neural network will generate informational insights to help you prepare for your consultation.
          </p>
        </div>

        <div className="grid lg:grid-cols-1 gap-12 max-w-3xl mx-auto">
          <form onSubmit={handleSubmit} className="card-premium bg-white shadow-2xl shadow-slate-200/50 relative overflow-hidden">
            <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-500/5 rounded-full blur-3xl"></div>

            <h2 className="text-xl font-black text-slate-900 mb-6 flex items-center gap-2">
              <span className="text-2xl">📝</span> Manifestation Description
            </h2>

            <textarea
              value={symptoms}
              onChange={(e) => setSymptoms(e.target.value)}
              placeholder="Example: 'Sudden onset of persistent localized pain in the lower right abdomen, accompanied by nausea and mild pyrexia...'"
              className="w-full p-6 bg-slate-50 border border-slate-100 rounded-3xl h-48 focus:ring-2 focus:ring-indigo-500 outline-none transition-all font-medium text-slate-700 placeholder:text-slate-300 resize-none shadow-inner"
              required
            />

            <div className="mt-8 flex flex-col md:flex-row items-center gap-6">
              <button
                type="submit"
                disabled={isLoading}
                className="w-full btn-premium py-4 font-black tracking-widest shadow-xl shadow-indigo-100 flex items-center justify-center gap-3"
              >
                {isLoading ? (
                  <>
                    <svg className="animate-spin h-5 w-5 text-white" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
                    <span>Processing Neural Map...</span>
                  </>
                ) : (
                  <>
                    <span>🧠</span>
                    <span>Generate Insights</span>
                  </>
                )}
              </button>
            </div>

            <p className="mt-6 text-center text-[10px] text-slate-400 font-bold uppercase tracking-widest px-8 leading-relaxed">
              ⚠️ Information generated by this utility is for preliminary assessment only and does not constitute a formal medical diagnosis. Always consult a certified professional.
            </p>
          </form>

          {result && (
            <div className="card-premium bg-slate-900 border-none shadow-2xl shadow-indigo-900/10 text-white animate-in zoom-in duration-500 relative overflow-hidden">
              <div className="absolute top-0 right-0 w-64 h-64 bg-cyan-500/10 rounded-full blur-[80px] -mr-32 -mt-32"></div>
              <div className="absolute bottom-0 left-0 w-48 h-48 bg-indigo-600/10 rounded-full blur-[80px] -ml-24 -mb-24"></div>

              <div className="relative z-10">
                <div className="flex items-center justify-between mb-8 pb-4 border-b border-white/5">
                  <h2 className="text-2xl font-black tracking-tight text-white flex items-center gap-3">
                    <span className="text-3xl">🔬</span> AI Findings Report
                  </h2>
                  <span className="px-3 py-1 bg-white/10 rounded-full text-[10px] font-black uppercase tracking-widest border border-white/10">Version 4.2.0</span>
                </div>

                <div className="text-slate-300 font-medium leading-[1.8] text-lg whitespace-pre-wrap selection:bg-indigo-500/30">
                  {result}
                </div>

                <div className="mt-12 flex items-center justify-center p-6 bg-white/5 rounded-[32px] border border-white/5">
                  <p className="text-xs text-slate-400 text-center font-bold tracking-tight">
                    Ready to discuss these findings? <Link to="/find-doctors" className="text-cyan-400 hover:text-white transition-colors underline underline-offset-4 ml-1">Connect with a specialist now.</Link>
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default SymptomCheckerPage;